 - name: Instalando pacote UBUNTU
   apt:
     deb: /root/puppet5-release-xenial.deb
   when: ansible_os_family == "Debian"

 - name: Iniciando o agent
   apt:
     name: puppet-agent
     state: present
     update_cache: yes
   when: ansible_os_family == "Debian"  

