---

 - name: Desafio Completo
   hosts: all
   tasks:

   - name: Parando o serviço Nginx
     service:
       name: nginx
       state: stopped
     ignore_errors: true

   - name: Removendo serviço Nginx
     apt: 
       name: nginx* 
       state: absent
     when: ansible_distribution == "Ubuntu"

   - name: removendo o serviço CENTOS
     yum: 
       name: nginx* 
       state: absent
     when: ansible_distribution == "CentOS"

   - name: Instalando arquivos - UBUNTU
     apt:
       name: "{{ item }}"
       state: present
       update_cache: yes
     with_items:
     - "apache2"
     - "libapache2-mod-php7.0"
     - "php7.0"
     when: ansible_distribution == "Ubuntu"

   - name: Instalando pacotes CENTOS
     yum:
       name: "{{ item }}"
       state: present
     with_items: 
     - "httpd"
     - "php"
     notify: httpd
     when: ansible_distribution == "CentOS"

   - name: Habilitando modulo apache2
     command: a2enmod php7.0
     notify: apache
     when: ansible_distribution == "Ubuntu"

   - name: Copiando index.php
     copy:
       src: /root/index.php
       dest: /var/www/html/index.php

   handlers: 
   - name: apache
     service:
       name: apache2
       state: restarted

   - name: httpd
     service:
       name: httpd
       state: restarted     
