---

- name: Testando Ansible
  hosts: all
  tasks:

  - name: Criando um usuario
    user: name={{ username }} shell=/bin/bash create_home=yes
    ignore_erros: true

  - name: Instalando Pacotes - Ubuntu
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
    - "cowsay"
    - "fortunes-br"
    - "figlet"
    - "nginx"
    notify: restart
    when: ansible_distribution == "Ubuntu"

  - name: Instalando EPEL - CENTOS
    yum: name=epel-release state=present
    when: ansible_distribution == "CentOS" 

  - name: instalando pacotes - CENTOS
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - "cowsay"
    - "figlet"
    - "nginx"
    notify: restart
    when: ansible_distribution == "CentOS"

  - name: Garantir DNS Local
    lineinfile:
      path: /etc/hosts 
      line: "{{ item }}"
    with_items: 
    - "192.168.99.10 devops.salas4linux.com.br devops"
    - "192.168.99.20 devops.salas4linux.com.br docker"
    - "192.168.99.30 devops.salas4linux.com.br automation"

 
  - name: Garantindo a Variavel PATH
    lineinfile:
      path: /etc/profile
      line: "export PATH=$PATH:/usr/games"
      state: present

  - name: Verificando Memoria
    command: free -h

  - name: Instalando pacote sl
    apt: name=sl state=absent update_cache=yes
    when: ansible_distribution == "Ubuntu"

  - name: Movendo arquivo
    copy: 
      src: /root/bashrc
      dest: /root/.bashrc

  handlers:
  - name: restart
    service:
      name: nginx
      state: restarted
